BEGIN;
-- Generated from contracts/sdk_capability_schemas.json; do not hand-edit.
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.cancel', 'Drive Scanner v2.1: request cancellation of one active owned scan.', 'http',
  'http://100.85.253.44:8460/api/scans/{scan_id}/cancel', 'POST',
  'json_body', 'hammer',
  '{"additionalProperties":false,"properties":{"reason":{"maxLength":500,"minLength":20,"type":"string"},"scan_id":{"minimum":1,"type":"integer"}},"required":["scan_id","reason"],"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"scan_id":{"minimum":1,"type":"integer"},"status":{"const":"cancellation_requested"}},"required":["api_version","status","scan_id"],"type":"object"}'::jsonb,
  'tier:2', 1.0, 2, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.domains', 'Drive Scanner v2.1: per-scan content-domain distribution.', 'http',
  'http://100.85.253.44:8460/api/domains', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"domains":{"type":"array"},"scan_id":{"type":["integer","null"]},"total_domains":{"minimum":0,"type":"integer"}},"required":["api_version","scan_id","domains","total_domains"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  20, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.duplicates', 'Drive Scanner v2.1: per-scan duplicate clusters and reclaim estimate.', 'http',
  'http://100.85.253.44:8460/api/duplicates', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"clusters":{"type":"array"},"scan_id":{"type":["integer","null"]},"total_clusters":{"minimum":0,"type":"integer"},"total_wasted_bytes":{"minimum":0,"type":"integer"}},"required":["api_version","scan_id","clusters","total_clusters","total_wasted_bytes"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.files', 'Drive Scanner v2.1: redacted per-scan file findings and scores.', 'http',
  'http://100.85.253.44:8460/api/files', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"domain":{"type":"string"},"extension":{"type":"string"},"limit":{"maximum":1000,"minimum":1,"type":"integer"},"offset":{"minimum":0,"type":"integer"},"scan_id":{"minimum":1,"type":"integer"},"search":{"maxLength":200,"type":"string"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"count":{"minimum":0,"type":"integer"},"files":{"items":{"additionalProperties":false,"properties":{"file":{"additionalProperties":false,"properties":{"accessed_at":{"type":["string","null"]},"created_at":{"type":["string","null"]},"display_path":{"type":"string"},"drive":{"type":"string"},"extension":{"type":["string","null"]},"filename":{"type":["string","null"]},"id":{"type":["integer","null"]},"is_binary":{"type":"boolean"},"mime_type":{"type":["string","null"]},"modified_at":{"type":["string","null"]},"path_id":{"pattern":"^[a-f0-9]{20}$","type":"string"},"protected":{"type":"boolean"},"scan_id":{"type":["integer","null"]},"size_bytes":{"minimum":0,"type":"integer"}},"required":["path_id","display_path","protected","filename","size_bytes"],"type":"object"},"score":{"type":["object","null"]}},"required":["file","score"],"type":"object"},"type":"array"},"scan_id":{"type":["integer","null"]}},"required":["api_version","scan_id","files","count"],"type":"object"}'::jsonb,
  'tier:1', 1.0, 1, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.health', 'Drive Scanner v2.1: authenticated service and subsystem health.', 'http',
  'http://100.85.253.44:8460/health', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"active_scan_ids":{"items":{"minimum":1,"type":"integer"},"type":"array"},"api_version":{"const":"2.1"},"database":{"type":"string"},"latest_scan":{"type":["object","null"]},"status":{"enum":["healthy","degraded","unhealthy"]},"subsystems":{"type":"object"},"total_scans":{"minimum":0,"type":"integer"},"version":{"type":"string"}},"required":["api_version","status","version","database","total_scans","active_scan_ids","subsystems"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  10, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.proposals', 'Drive Scanner v2.1: read-only completion and new-build proposals.', 'http',
  'http://100.85.253.44:8460/api/proposals', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"kind":{"enum":["completion","new_build"]},"limit":{"maximum":1000,"minimum":1,"type":"integer"},"scan_id":{"minimum":1,"type":"integer"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"completion":{"minimum":0,"type":"integer"},"count":{"minimum":0,"type":"integer"},"kind":{"type":["string","null"]},"new_build":{"minimum":0,"type":"integer"},"proposals":{"type":"array"},"queue_supported":{"const":false},"scan_id":{"type":["integer","null"]}},"required":["api_version","scan_id","proposals","count","completion","new_build","queue_supported"],"type":"object"}'::jsonb,
  'tier:1', 1.0, 1, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.recommendations', 'Drive Scanner v2.1: read-only prioritized storage recommendations.', 'http',
  'http://100.85.253.44:8460/api/recommendations', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"recommendations":{"type":"array"},"scan_id":{"type":["integer","null"]},"total":{"minimum":0,"type":"integer"}},"required":["api_version","scan_id","recommendations","total"],"type":"object"}'::jsonb,
  'tier:1', 1.0, 1, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.results', 'Drive Scanner v2.1: immutable summary and stage evidence for one scan.', 'http',
  'http://100.85.253.44:8460/api/scan/{scan_id}/results', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"required":["scan_id"],"type":"object"}'::jsonb, '{"$defs":{"stage":{"additionalProperties":false,"properties":{"completed_at":{"type":["string","null"]},"detail":{"type":["string","null"]},"scan_id":{"type":"integer"},"stage":{"type":"string"},"started_at":{"type":["string","null"]},"status":{"enum":["running","passed","failed","degraded","skipped","cancelled"]},"warning_count":{"minimum":0,"type":"integer"}},"required":["scan_id","stage","status","warning_count"],"type":"object"}},"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"avg_importance":{"type":"number"},"avg_quality":{"type":"number"},"domain_distribution":{"type":"object"},"duplicate_clusters":{"minimum":0,"type":"integer"},"duration_seconds":{"minimum":0,"type":"number"},"files_classified":{"minimum":0,"type":"integer"},"high_risk_count":{"minimum":0,"type":"integer"},"recommendation_count":{"minimum":0,"type":"integer"},"scan_id":{"type":"integer"},"sensitive_count":{"minimum":0,"type":"integer"},"stages":{"items":{"$ref":"#/$defs/stage"},"type":"array"},"status":{"type":"string"},"top_domains":{"type":"array"},"total_files":{"minimum":0,"type":"integer"},"total_size_bytes":{"minimum":0,"type":"integer"},"wasted_bytes":{"minimum":0,"type":"integer"}},"required":["api_version","scan_id","status","total_files","stages"],"type":"object"}'::jsonb,
  'tier:1', 1.0, 1, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  30, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.scan', 'Drive Scanner v2.1: start a guarded scan and return a durable scan id.', 'http',
  'http://100.85.253.44:8460/api/scan/start', 'POST',
  'json_body', 'hammer',
  '{"additionalProperties":false,"properties":{"paths":{"items":{"maxLength":1024,"minLength":1,"type":"string"},"maxItems":32,"minItems":1,"type":"array"},"profile":{"default":"INTEL_FAST","enum":["INTELLIGENCE","INTEL_FAST","INTEL_SECURITY","INTEL_COMPLIANCE","INTEL_OILFIELD","DEDUP"]}},"required":["paths"],"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"accepted_at":{"type":"string"},"api_version":{"const":"2.1"},"normalized_roots":{"items":{"type":"string"},"type":"array"},"profile":{"type":"string"},"run_id":{"type":"string"},"scan_id":{"minimum":1,"type":"integer"},"stages_url":{"type":"string"},"status":{"const":"accepted"},"status_url":{"type":"string"}},"required":["api_version","status","scan_id","run_id","profile","normalized_roots","status_url","stages_url","accepted_at"],"type":"object"}'::jsonb,
  'tier:2', 1.0, 2, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  120, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.scan_status', 'Drive Scanner v2.1: status and stages for one durable scan id.', 'http',
  'http://100.85.253.44:8460/api/scans/{scan_id}/status', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"required":["scan_id"],"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"completed_at":{"type":["string","null"]},"config":{"type":["string","null"]},"drives":{"type":"string"},"duration_seconds":{"minimum":0,"type":["number","null"]},"files_classified":{"minimum":0,"type":"integer"},"files_skipped":{"minimum":0,"type":"integer"},"id":{"minimum":1,"type":"integer"},"profile":{"type":"string"},"stages":{"items":{"additionalProperties":false,"properties":{"completed_at":{"type":["string","null"]},"detail":{"type":["string","null"]},"scan_id":{"minimum":1,"type":"integer"},"stage":{"type":"string"},"started_at":{"type":["string","null"]},"status":{"enum":["running","passed","failed","degraded","skipped","cancelled"]},"warning_count":{"minimum":0,"type":"integer"}},"required":["scan_id","stage","status","warning_count"],"type":"object"},"type":"array"},"started_at":{"type":"string"},"status":{"enum":["running","completed","completed_with_warnings","degraded","failed","cancelled"]},"total_files":{"minimum":0,"type":"integer"},"total_size_bytes":{"minimum":0,"type":"integer"}},"required":["api_version","id","status","stages"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  15, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.stages', 'Drive Scanner v2.1: per-stage outcomes for one durable scan id.', 'http',
  'http://100.85.253.44:8460/api/scans/{scan_id}/stages', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"required":["scan_id"],"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"scan_id":{"minimum":1,"type":"integer"},"stages":{"items":{"additionalProperties":false,"properties":{"completed_at":{"type":["string","null"]},"detail":{"type":["string","null"]},"scan_id":{"minimum":1,"type":"integer"},"stage":{"type":"string"},"started_at":{"type":["string","null"]},"status":{"enum":["running","passed","failed","degraded","skipped","cancelled"]},"warning_count":{"minimum":0,"type":"integer"}},"required":["scan_id","stage","status","warning_count"],"type":"object"},"type":"array"}},"required":["api_version","scan_id","stages"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  15, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.status', 'Drive Scanner v2.1: latest scan status for discovery only.', 'http',
  'http://100.85.253.44:8460/api/scan/status', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"completed_at":{"type":["string","null"]},"config":{"type":["string","null"]},"drives":{"type":"string"},"duration_seconds":{"minimum":0,"type":["number","null"]},"files_classified":{"minimum":0,"type":"integer"},"files_skipped":{"minimum":0,"type":"integer"},"id":{"type":["integer","null"]},"profile":{"type":"string"},"started_at":{"type":"string"},"status":{"enum":["no_scans","running","completed","completed_with_warnings","degraded","failed","cancelled"]},"total_files":{"minimum":0,"type":"integer"},"total_size_bytes":{"minimum":0,"type":"integer"}},"required":["api_version","status"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  15, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();
INSERT INTO arcanum_sdk.sdk_capabilities (
  id, description, handler_kind, target_url, target_method, args_mode,
  target_node, input_schema_json, output_schema_json, required_scope,
  rate_cost, danger_tier, schema_version, is_builtin, health_status,
  requires_guard_scan, never_archive, lifecycle_status, option_projections,
  default_timeout_seconds, never_breaker_block, static_headers, health_reason,
  created_at, updated_at
) VALUES (
  'echo.drivescan.storage', 'Drive Scanner v2.1: filesystem capacity summary without fabricated SMART health.', 'http',
  'http://100.85.253.44:8460/api/storage/summary', 'GET',
  'query', 'hammer',
  '{"additionalProperties":false,"properties":{"scan_id":{"minimum":1,"type":"integer"}},"type":"object"}'::jsonb, '{"additionalProperties":false,"properties":{"api_version":{"const":"2.1"},"drives":{"type":"array"},"health_source":{"enum":["filesystem_only","filesystem_capacity"]},"scan_id":{"type":["integer","null"]}},"required":["api_version","scan_id","drives","health_source"],"type":"object"}'::jsonb,
  'tier:0', 1.0, 0, 2, false, 'amber',
  true, true, 'active', '[]'::jsonb,
  20, false, '{}'::jsonb,
  'pending governed post-deployment invocation and schema validation',
  now(), now()
) ON CONFLICT (id) DO UPDATE SET
  description = EXCLUDED.description,
  handler_kind = EXCLUDED.handler_kind,
  target_url = EXCLUDED.target_url,
  target_method = EXCLUDED.target_method,
  args_mode = EXCLUDED.args_mode,
  target_node = EXCLUDED.target_node,
  input_schema_json = EXCLUDED.input_schema_json,
  output_schema_json = EXCLUDED.output_schema_json,
  required_scope = EXCLUDED.required_scope,
  danger_tier = EXCLUDED.danger_tier,
  schema_version = EXCLUDED.schema_version,
  health_status = 'amber',
  health_reason = EXCLUDED.health_reason,
  default_timeout_seconds = EXCLUDED.default_timeout_seconds,
  requires_guard_scan = true,
  never_archive = true,
  lifecycle_status = 'active',
  updated_at = now();

-- Fail closed if the expected capability family is incomplete.
DO $$
BEGIN
  IF (SELECT count(*) FROM arcanum_sdk.sdk_capabilities WHERE id IN ('echo.drivescan.cancel', 'echo.drivescan.domains', 'echo.drivescan.duplicates', 'echo.drivescan.files', 'echo.drivescan.health', 'echo.drivescan.proposals', 'echo.drivescan.recommendations', 'echo.drivescan.results', 'echo.drivescan.scan', 'echo.drivescan.scan_status', 'echo.drivescan.stages', 'echo.drivescan.status', 'echo.drivescan.storage')) <> 13 THEN
    RAISE EXCEPTION 'Drive Scanner capability reconciliation incomplete';
  END IF;
END $$;
COMMIT;
